name: Test Project # name of work flow
on: [push, workflow_dispatch] # event when it should be triggered. Push is for any push event in repo, workflow dispatch is for any manual event. You can pass multiple events
jobs:
  test:
    runs-on: ubuntu-latest # runner where work flow can be hosted
    steps:
      - name: Get Code
        uses: actions/checkout@v3 # pre existing actions which has incorporated the logic
      - name: Install Node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: [test] # depends on test job to finish first
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: deploy
        run: echo "Deploying to the server"
    